application: discgolfhub
version: 02-alpha
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets
  
- url: /connect
  static_dir: connect
  
- url: /javascript
  static_dir: javascript
  
- url: /load
  script: dataloader.py
  login: admin


- url: /rapi
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: discgolfhub.py
